# Form implementation generated from reading ui file 'about_add_on.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(488, 630)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.closeWindow = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeWindow.setGeometry(QtCore.QRect(190, 560, 111, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.closeWindow.setFont(font)
        self.closeWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.closeWindow.setIconSize(QtCore.QSize(24, 26))
        self.closeWindow.setObjectName("closeWindow")
        self.addonVersionNumber = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.addonVersionNumber.setGeometry(QtCore.QRect(390, 40, 71, 31))
        self.addonVersionNumber.setStyleSheet(
            "QTextBrowser {\n"
            "    background: rgba(0, 0, 0, 0);  /* Completely transparent background */\n"
            "    border: none;  /* No border */\n"
            "    color: black;  /* Text color */\n"
            "}\n"
            ""
        )
        self.addonVersionNumber.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow
        )
        self.addonVersionNumber.setOpenExternalLinks(True)
        self.addonVersionNumber.setObjectName("addonVersionNumber")
        self.addonTitle = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.addonTitle.setGeometry(QtCore.QRect(80, 10, 221, 31))
        self.addonTitle.setStyleSheet(
            "QTextBrowser {\n"
            "    background: rgba(0, 0, 0, 0);  /* Completely transparent background */\n"
            "    border: none;  /* No border */\n"
            "    color: black;  /* Text color */\n"
            "}\n"
            ""
        )
        self.addonTitle.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow
        )
        self.addonTitle.setOpenExternalLinks(True)
        self.addonTitle.setObjectName("addonTitle")
        self.thumbsUpLikeAddOn = QtWidgets.QLabel(parent=self.centralwidget)
        self.thumbsUpLikeAddOn.setGeometry(QtCore.QRect(310, 10, 31, 31))
        self.thumbsUpLikeAddOn.setMouseTracking(True)
        self.thumbsUpLikeAddOn.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.thumbsUpLikeAddOn.setText("")
        self.thumbsUpLikeAddOn.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.thumbsUpLikeAddOn.setPixmap(QtGui.QPixmap("../img/rate.svg"))
        self.thumbsUpLikeAddOn.setScaledContents(True)
        self.thumbsUpLikeAddOn.setWordWrap(False)
        self.thumbsUpLikeAddOn.setOpenExternalLinks(True)
        self.thumbsUpLikeAddOn.setObjectName("thumbsUpLikeAddOn")
        self.githubLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.githubLabel.setGeometry(QtCore.QRect(360, 10, 31, 31))
        self.githubLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.githubLabel.setText("")
        self.githubLabel.setPixmap(QtGui.QPixmap("../img/github.png"))
        self.githubLabel.setScaledContents(True)
        self.githubLabel.setObjectName("githubLabel")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 461, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.aboutTab_0 = QtWidgets.QWidget()
        self.aboutTab_0.setObjectName("aboutTab_0")
        self.aboutAddonText_0 = QtWidgets.QScrollArea(parent=self.aboutTab_0)
        self.aboutAddonText_0.setGeometry(QtCore.QRect(0, 10, 441, 451))
        self.aboutAddonText_0.setWidgetResizable(True)
        self.aboutAddonText_0.setObjectName("aboutAddonText_0")
        self.aboutAddonTextScrollAreaWidgetContents_0 = QtWidgets.QWidget()
        self.aboutAddonTextScrollAreaWidgetContents_0.setGeometry(
            QtCore.QRect(0, 0, 439, 449)
        )
        self.aboutAddonTextScrollAreaWidgetContents_0.setObjectName(
            "aboutAddonTextScrollAreaWidgetContents_0"
        )
        self.textBrowser_2 = QtWidgets.QTextBrowser(
            parent=self.aboutAddonTextScrollAreaWidgetContents_0
        )
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 10, 421, 431))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.aboutAddonText_0.setWidget(self.aboutAddonTextScrollAreaWidgetContents_0)
        self.tabWidget.addTab(self.aboutTab_0, "")
        self.updateLog_1 = QtWidgets.QWidget()
        self.updateLog_1.setObjectName("updateLog_1")
        self.updateLogText_1 = QtWidgets.QScrollArea(parent=self.updateLog_1)
        self.updateLogText_1.setGeometry(QtCore.QRect(10, 10, 441, 451))
        self.updateLogText_1.setWidgetResizable(True)
        self.updateLogText_1.setObjectName("updateLogText_1")
        self.updateLogTextScrollAreaWidgetContents_1 = QtWidgets.QWidget()
        self.updateLogTextScrollAreaWidgetContents_1.setGeometry(
            QtCore.QRect(0, 0, 439, 449)
        )
        self.updateLogTextScrollAreaWidgetContents_1.setObjectName(
            "updateLogTextScrollAreaWidgetContents_1"
        )
        self.updateLogTextTextBrowser_1 = QtWidgets.QTextBrowser(
            parent=self.updateLogTextScrollAreaWidgetContents_1
        )
        self.updateLogTextTextBrowser_1.setGeometry(QtCore.QRect(10, 10, 421, 431))
        self.updateLogTextTextBrowser_1.setObjectName("updateLogTextTextBrowser_1")
        self.updateLogText_1.setWidget(self.updateLogTextScrollAreaWidgetContents_1)
        self.tabWidget.addTab(self.updateLog_1, "")
        self.addonLog_2 = QtWidgets.QWidget()
        self.addonLog_2.setObjectName("addonLog_2")
        self.addonLogText_2 = QtWidgets.QScrollArea(parent=self.addonLog_2)
        self.addonLogText_2.setGeometry(QtCore.QRect(10, 10, 441, 451))
        self.addonLogText_2.setWidgetResizable(True)
        self.addonLogText_2.setObjectName("addonLogText_2")
        self.addonLogScrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.addonLogScrollAreaWidgetContents_2.setGeometry(
            QtCore.QRect(0, 0, 439, 449)
        )
        self.addonLogScrollAreaWidgetContents_2.setObjectName(
            "addonLogScrollAreaWidgetContents_2"
        )
        self.addonLogTextBrowser_2 = QtWidgets.QTextBrowser(
            parent=self.addonLogScrollAreaWidgetContents_2
        )
        self.addonLogTextBrowser_2.setGeometry(QtCore.QRect(10, 10, 421, 431))
        self.addonLogTextBrowser_2.setObjectName("addonLogTextBrowser_2")
        self.addonLogText_2.setWidget(self.addonLogScrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.addonLog_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "About Bunseki"))
        self.closeWindow.setText(_translate("MainWindow", "close"))
        self.addonVersionNumber.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a href="https://github.com/christopher-chandler/bulk_generate_japanese_vocab_frequency/releases/tag/update_config_file"><span style=" font-size:18pt; font-style:italic; text-decoration: underline; color:#094fd1;">V.1.0.2</span></a></p></body></html>',
            )
        )
        self.addonTitle.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:15pt; font-weight:700;">Bunseki Frequency Japanese</span></p></body></html>',
            )
        )
        self.textBrowser_2.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-weight:700;"> </span><span style=" font-size:18pt; font-weight:700;">About</span><span style=" font-weight:700;">  </span></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">This anki add on is for generating frequency and word type data for a given field. </p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Checkout the config file or the offical github repo to find out how this add on works. </p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:700;"><br /></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:18pt; font-weight:700;">Credits</span> </p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;">© 2022-2024  <a href="https://github.com/christopher-chandler/bulk_generate_japanese_vocab_frequency"><span style=" text-decoration: underline; color:#094fd1;">Christopher Chandler</span></a></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;">Bunseki ships with the following third-party code:</p>\n'
                '<ul style="margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;">\n'
                '<li style=" margin-top:0px; margin-bottom:0px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;"> <a href="Bulk-Generate Japanese Vocab Frequency Ranking"><span style=" text-decoration: underline; color:#094fd1;">Bulk-Generate Japanese Vocab Frequency Ranking</span></a></li></ul>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;"> <img src=":/img/rate.png" /><span style=" font-weight:700;"> Thank you!</span> </p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;">My heartfelt thanks go out to everyone who has <span style=" font-weight:700;">supported</span> this add-on through their tips, contributions, or any other means. You guys rock! </p>\n'
                '<h3 style=" margin-top:14px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:18pt; font-weight:700;">License</span><span style=" font-size:large; font-weight:700;"> </span></h3>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;"><span style=" font-style:italic;">Bunseki</span> is <span style=" font-weight:700;">free and open-source</span> software. The add-on code that runs within Anki is released under the GNU AGPLv3 license, extended by a number of additional terms. For more information please see the license file that accompanied this program. </p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;">This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY. Please see the license file for more details. </p></body></html>',
            )
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.aboutTab_0), _translate("MainWindow", "About")
        )
        self.updateLogTextTextBrowser_1.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:'-apple-system','system-ui','Segoe UI','Noto Sans','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; font-size:18pt; font-weight:700; text-decoration: underline; text-decoration-color:#000000; color:#1f2328; background-color:#ffffff;\">v1.0.2</span></p>\n"
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:'-apple-system','system-ui','Segoe UI','Noto Sans','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; font-size:14pt; color:#1f2328; background-color:#ffffff;\">add function so that word type data can be added to a field alongside the frequency data </span></p>\n"
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:'-apple-system','system-ui','Segoe UI','Noto Sans','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; font-size:14pt; color:#1f2328; background-color:#ffffff;\">restructured the config file to include the new 03_word_type_output_field</span></p></body></html>",
            )
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.updateLog_1),
            _translate("MainWindow", "Update Log"),
        )
        self.addonLogTextBrowser_2.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;"><br /></p></body></html>',
            )
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.addonLog_2),
            _translate("MainWindow", "Add On Log"),
        )
