# Form implementation generated from reading ui file 'about_add_on.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(433, 467)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.closeWindow = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeWindow.setGeometry(QtCore.QRect(310, 390, 111, 41))
        self.closeWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.closeWindow.setIconSize(QtCore.QSize(24, 26))
        self.closeWindow.setObjectName("closeWindow")
        self.AboutAddOnText = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.AboutAddOnText.setGeometry(QtCore.QRect(10, 60, 411, 331))
        self.AboutAddOnText.setWidgetResizable(True)
        self.AboutAddOnText.setObjectName("AboutAddOnText")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 409, 329))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.scrollAreaWidgetContents)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 391, 301))
        self.textBrowser.setObjectName("textBrowser")
        self.AboutAddOnText.setWidget(self.scrollAreaWidgetContents)
        self.AddOnVersionNumber = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.AddOnVersionNumber.setGeometry(QtCore.QRect(360, 30, 51, 31))
        self.AddOnVersionNumber.setStyleSheet(
            "QTextBrowser {\n"
            "    background: rgba(0, 0, 0, 0);  /* Completely transparent background */\n"
            "    border: none;  /* No border */\n"
            "    color: black;  /* Text color */\n"
            "}\n"
            ""
        )
        self.AddOnVersionNumber.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow
        )
        self.AddOnVersionNumber.setOpenExternalLinks(True)
        self.AddOnVersionNumber.setObjectName("AddOnVersionNumber")
        self.AddOnTitle = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.AddOnTitle.setGeometry(QtCore.QRect(40, 0, 281, 31))
        self.AddOnTitle.setStyleSheet(
            "QTextBrowser {\n"
            "    background: rgba(0, 0, 0, 0);  /* Completely transparent background */\n"
            "    border: none;  /* No border */\n"
            "    color: black;  /* Text color */\n"
            "}\n"
            ""
        )
        self.AddOnTitle.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow
        )
        self.AddOnTitle.setOpenExternalLinks(True)
        self.AddOnTitle.setObjectName("AddOnTitle")
        self.ThumbsUpLikeAddOn = QtWidgets.QLabel(parent=self.centralwidget)
        self.ThumbsUpLikeAddOn.setGeometry(QtCore.QRect(330, 0, 31, 31))
        self.ThumbsUpLikeAddOn.setMouseTracking(True)
        self.ThumbsUpLikeAddOn.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.ThumbsUpLikeAddOn.setText("")
        self.ThumbsUpLikeAddOn.setPixmap(QtGui.QPixmap(f" rate.svg"))
        self.ThumbsUpLikeAddOn.setScaledContents(True)
        self.ThumbsUpLikeAddOn.setOpenExternalLinks(True)
        self.ThumbsUpLikeAddOn.setObjectName("ThumbsUpLikeAddOn")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 0, 31, 31))
        self.label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/github.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.AboutAddOnText, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.closeWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "About Bunseki"))
        self.closeWindow.setText(_translate("MainWindow", "close"))

        self.textBrowser.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-weight:700;"> </span><span style=" font-size:18pt; font-weight:700;">About</span><span style=" font-weight:700;">  </span></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">This anki add on is for generating frequency and word type data for a given field. </p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Checkout the config file or the offical github repo to find out how this add on works. </p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:700;"><br /></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:18pt; font-weight:700;">Credits</span> </p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;">© 2022-2024  <a href="https://github.com/christopher-chandler/bulk_generate_japanese_vocab_frequency"><span style=" text-decoration: underline; color:#094fd1;">Christopher Chandler</span></a></p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;">Bunseki ships with the following third-party code:</p>\n'
                '<ul style="margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;">\n'
                '<li style=" margin-top:0px; margin-bottom:0px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;"> <a href="Bulk-Generate Japanese Vocab Frequency Ranking"><span style=" text-decoration: underline; color:#094fd1;">Bulk-Generate Japanese Vocab Frequency Ranking</span></a></li></ul>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;"> <img src=":/img/rate.png" /><span style=" font-weight:700;"> Thank you!</span> </p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;">My heartfelt thanks go out to everyone who has <span style=" font-weight:700;">supported</span> this add-on through their tips, contributions, or any other means. You guys rock! </p>\n'
                '<h3 style=" margin-top:14px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:18pt; font-weight:700;">License</span><span style=" font-size:large; font-weight:700;"> </span></h3>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;"><span style=" font-style:italic;">Bunseki</span> is <span style=" font-weight:700;">free and open-source</span> software. The add-on code that runs within Anki is released under the GNU AGPLv3 license, extended by a number of additional terms. For more information please see the license file that accompanied this program. </p>\n'
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;">This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY. Please see the license file for more details. </p></body></html>',
            )
        )
        self.AddOnVersionNumber.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><a href="https://github.com/christopher-chandler/bulk_generate_japanese_vocab_frequency/releases/tag/update_config_file"><span style=" font-size:14pt; font-style:italic; text-decoration: underline; color:#094fd1;">V.1.0.2</span></a></p></body></html>',
            )
        )
        self.AddOnTitle.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'.AppleSystemUIFont'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:15pt; font-weight:700;">About Bunseki Frequency Japanese</span></p></body></html>',
            )
        )
